// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tftwebapinew.Database;

#nullable disable

namespace tftwebapinew.Migrations
{
    [DbContext(typeof(tftdatabaseContext))]
    partial class tftdatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("characterclass", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("CharacterID");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.HasKey("CharacterId", "ClassId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClassId" }, "ClassID");

                    b.ToTable("characterclass", (string)null);
                });

            modelBuilder.Entity("tftwebapinew.Models.PostAnomaly", b =>
                {
                    b.Property<int>("AnomalyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnomalyEffect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnomalyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnomalyId");

                    b.ToTable("Anomalies");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostAugment", b =>
                {
                    b.Property<int>("AugmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AugmentEffect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AugmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AugmentRarity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AugmentId");

                    b.ToTable("Augments");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostBoard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Board_id")
                        .HasColumnType("int");

                    b.Property<string>("Boardname")
                        .HasColumnType("longtext");

                    b.Property<int>("PostUserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PostUserId");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostBoardHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Board_id")
                        .HasColumnType("int");

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.Property<int?>("PostCharacterCharacterID")
                        .HasColumnType("int");

                    b.Property<int>("hex_x")
                        .HasColumnType("int");

                    b.Property<int>("hex_y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostCharacterCharacterID");

                    b.ToTable("boardHexes");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostCharacter", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AbilityPower")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<double>("AttackSpeed")
                        .HasColumnType("double");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Characterimageblob")
                        .HasColumnType("longtext");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Damage1")
                        .HasColumnType("int");

                    b.Property<int>("Damage2")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Health1")
                        .HasColumnType("int");

                    b.Property<int>("Health2")
                        .HasColumnType("int");

                    b.Property<int>("MagicResist")
                        .HasColumnType("int");

                    b.Property<int>("ManaMax")
                        .HasColumnType("int");

                    b.Property<int>("ManaStart")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.HasKey("CharacterID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostClass", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BasicEffect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Classimageblob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClassId");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostClassLevelBonus", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("BonusEffect")
                        .HasColumnType("longtext");

                    b.Property<int?>("CharacterCount")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "Level");

                    b.ToTable("Classlevelbonus");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostFullitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActiveEffect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fullitemimageblob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Halfitemeffect1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Halfitemeffect2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bonuseffect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bonuseffect1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("bonuseffect2")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FullItems");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostFullitem_Partialitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FullItemId")
                        .HasColumnType("int");

                    b.Property<int>("PartialItemId1")
                        .HasColumnType("int");

                    b.Property<int>("PartialItemId2")
                        .HasColumnType("int");

                    b.Property<int?>("PostFullitemId")
                        .HasColumnType("int");

                    b.Property<int?>("PostFullitem_PartialitemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostFullitemId");

                    b.HasIndex("PostFullitem_PartialitemId");

                    b.ToTable("FullItems_PartialItems");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostPartialitem", b =>
                {
                    b.Property<int>("partial_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("effect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("halfitemimageBlob")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("partial_item_id");

                    b.ToTable("PartialItems");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("characterclass", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostCharacter", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("characterclass_ibfk_1");

                    b.HasOne("tftwebapinew.Models.PostClass", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("characterclass_ibfk_2");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostBoard", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostUser", "PostUser")
                        .WithMany("Boards")
                        .HasForeignKey("PostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostUser");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostBoardHex", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostCharacter", null)
                        .WithMany("BoardHexes")
                        .HasForeignKey("PostCharacterCharacterID");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostClassLevelBonus", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostClass", "Class")
                        .WithMany("Classlevelbonus")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostFullitem_Partialitem", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostFullitem", null)
                        .WithMany("Fullitem_Partialitems")
                        .HasForeignKey("PostFullitemId");

                    b.HasOne("tftwebapinew.Models.PostFullitem_Partialitem", null)
                        .WithMany("Fullitem_Partialitems")
                        .HasForeignKey("PostFullitem_PartialitemId");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostUser", b =>
                {
                    b.HasOne("tftwebapinew.Models.PostPermission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostCharacter", b =>
                {
                    b.Navigation("BoardHexes");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostClass", b =>
                {
                    b.Navigation("Classlevelbonus");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostFullitem", b =>
                {
                    b.Navigation("Fullitem_Partialitems");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostFullitem_Partialitem", b =>
                {
                    b.Navigation("Fullitem_Partialitems");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostPermission", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("tftwebapinew.Models.PostUser", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
